import { User, Product, Category, FlashSale, BannerSlide, Order } from '@/types';

export const mockUsers: User[] = [
  {
    id: 'admin-1',
    email: 'admin@demo.com',
    name: 'Admin Demo',
    role: 'admin',
    loyaltyPoints: 0,
    createdAt: '2024-01-01T00:00:00Z',
    isActive: true,
  },
  {
    id: 'user-1',
    email: 'user@demo.com',
    name: 'User Demo',
    phone: '+33612345678',
    address: '123 Rue de la Paix',
    city: 'Paris',
    role: 'user',
    loyaltyPoints: 250,
    createdAt: '2024-01-15T00:00:00Z',
    isActive: true,
  },
];

export const mockCategories: Category[] = [
  { id: 'cat-1', name: 'iPhones', slug: 'iphones', icon: '📱', productCount: 15 },
  { id: 'cat-2', name: 'Android', slug: 'android', icon: '🤖', productCount: 25 },
  { id: 'cat-3', name: 'Tablettes', slug: 'tablettes', icon: '📱', productCount: 10 },
  { id: 'cat-4', name: 'Ordinateurs', slug: 'ordinateurs', icon: '💻', productCount: 12 },
  { id: 'cat-5', name: 'AirPods', slug: 'airpods', icon: '🎧', productCount: 8 },
  { id: 'cat-6', name: 'Accessoires', slug: 'accessoires', icon: '🔌', productCount: 30 },
];

export const mockProducts: Product[] = [
  {
    id: 'prod-1',
    name: 'iPhone 15 Pro Max',
    description: 'Le summum de l\'innovation Apple avec puce A17 Pro, caméra 48MP et écran Super Retina XDR',
    price: 1299,
    originalPrice: 1499,
    category: 'iphones',
    images: [
      'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800',
      'https://images.unsplash.com/photo-1695048133082-f6f47c02b38a?w=800',
    ],
    inStock: true,
    stockQuantity: 25,
    specifications: {
      'Écran': '6.7" Super Retina XDR',
      'Processeur': 'A17 Pro',
      'RAM': '8GB',
      'Stockage': '256GB',
      'Caméra': '48MP + 12MP + 12MP',
      'Batterie': '4422 mAh',
    },
    featured: true,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'prod-2',
    name: 'Samsung Galaxy S24 Ultra',
    description: 'Smartphone premium avec S Pen, écran Dynamic AMOLED 2X et zoom 100x',
    price: 1199,
    category: 'android',
    images: [
      'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=800',
    ],
    inStock: true,
    stockQuantity: 30,
    specifications: {
      'Écran': '6.8" Dynamic AMOLED 2X',
      'Processeur': 'Snapdragon 8 Gen 3',
      'RAM': '12GB',
      'Stockage': '512GB',
      'Caméra': '200MP + 50MP + 12MP + 10MP',
      'Batterie': '5000 mAh',
    },
    featured: true,
    createdAt: '2024-01-02T00:00:00Z',
  },
  {
    id: 'prod-3',
    name: 'Google Pixel 8 Pro',
    description: 'Intelligence artificielle avancée, photographie exceptionnelle et Android pur',
    price: 899,
    category: 'android',
    images: [
      'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800',
    ],
    inStock: true,
    stockQuantity: 20,
    specifications: {
      'Écran': '6.7" LTPO OLED',
      'Processeur': 'Google Tensor G3',
      'RAM': '12GB',
      'Stockage': '256GB',
      'Caméra': '50MP + 48MP + 48MP',
      'Batterie': '5050 mAh',
    },
    featured: false,
    createdAt: '2024-01-03T00:00:00Z',
  },
  {
    id: 'prod-4',
    name: 'iPad Pro 12.9"',
    description: 'Tablette professionnelle avec puce M2, écran Liquid Retina XDR',
    price: 1099,
    originalPrice: 1299,
    category: 'tablettes',
    images: [
      'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800',
    ],
    inStock: true,
    stockQuantity: 15,
    specifications: {
      'Écran': '12.9" Liquid Retina XDR',
      'Processeur': 'Apple M2',
      'RAM': '8GB',
      'Stockage': '256GB',
      'Connectivité': 'Wi-Fi 6E + 5G',
      'Autonomie': '10 heures',
    },
    featured: true,
    createdAt: '2024-01-04T00:00:00Z',
  },
  {
    id: 'prod-5',
    name: 'MacBook Air M2',
    description: 'Ordinateur portable ultra-fin avec puce M2, écran Liquid Retina',
    price: 1199,
    category: 'ordinateurs',
    images: [
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800',
    ],
    inStock: true,
    stockQuantity: 18,
    specifications: {
      'Écran': '13.6" Liquid Retina',
      'Processeur': 'Apple M2',
      'RAM': '8GB',
      'Stockage': '256GB SSD',
      'Autonomie': '18 heures',
      'Poids': '1.24 kg',
    },
    featured: false,
    createdAt: '2024-01-05T00:00:00Z',
  },
  {
    id: 'prod-6',
    name: 'AirPods Pro 2',
    description: 'Écouteurs avec réduction de bruit active adaptative et audio spatial',
    price: 249,
    category: 'airpods',
    images: [
      'https://images.unsplash.com/photo-1606841837239-c5a1a4a07af7?w=800',
    ],
    inStock: true,
    stockQuantity: 50,
    specifications: {
      'Type': 'Intra-auriculaire',
      'Réduction de bruit': 'Active adaptative',
      'Autonomie': '6h (ANC activé)',
      'Boîtier': '30h d\'autonomie',
      'Résistance': 'IPX4',
      'Audio': 'Spatial personnalisé',
    },
    featured: false,
    createdAt: '2024-01-06T00:00:00Z',
  },
  {
    id: 'prod-7',
    name: 'OnePlus 12',
    description: 'Smartphone haut de gamme avec charge ultra-rapide 100W',
    price: 799,
    category: 'android',
    images: [
      'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800',
    ],
    inStock: true,
    stockQuantity: 22,
    specifications: {
      'Écran': '6.82" AMOLED 120Hz',
      'Processeur': 'Snapdragon 8 Gen 3',
      'RAM': '16GB',
      'Stockage': '512GB',
      'Caméra': '50MP + 48MP + 32MP',
      'Batterie': '5400 mAh',
    },
    featured: false,
    createdAt: '2024-01-07T00:00:00Z',
  },
  {
    id: 'prod-8',
    name: 'iPhone 14',
    description: 'iPhone performant avec écran Super Retina XDR et puce A15 Bionic',
    price: 799,
    originalPrice: 899,
    category: 'iphones',
    images: [
      'https://images.unsplash.com/photo-1663499482523-1c0d3118c9f7?w=800',
    ],
    inStock: true,
    stockQuantity: 35,
    specifications: {
      'Écran': '6.1" Super Retina XDR',
      'Processeur': 'A15 Bionic',
      'RAM': '6GB',
      'Stockage': '128GB',
      'Caméra': '12MP + 12MP',
      'Batterie': '3279 mAh',
    },
    featured: false,
    createdAt: '2024-01-08T00:00:00Z',
  },
];

export const mockFlashSales: FlashSale[] = [
  {
    id: 'flash-1',
    productId: 'prod-1',
    product: mockProducts[0],
    discountPrice: 1099,
    discountPercentage: 20,
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(), // +24h
    stock: 10,
    isActive: true,
  },
  {
    id: 'flash-2',
    productId: 'prod-4',
    product: mockProducts[3],
    discountPrice: 899,
    discountPercentage: 25,
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 12 * 60 * 60 * 1000).toISOString(), // +12h
    stock: 5,
    isActive: true,
  },
  {
    id: 'flash-3',
    productId: 'prod-8',
    product: mockProducts[7],
    discountPrice: 699,
    discountPercentage: 15,
    startDate: new Date().toISOString(),
    endDate: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(), // +6h
    stock: 15,
    isActive: true,
  },
];

export const mockBanners: BannerSlide[] = [
  {
    id: 'banner-1',
    productId: 'prod-1',
    product: mockProducts[0],
    title: 'iPhone 15 Pro Max',
    subtitle: 'Titanium. Si puissant. Si léger.',
    imageUrl: mockProducts[0].images[0],
    order: 1,
    isActive: true,
  },
  {
    id: 'banner-2',
    productId: 'prod-2',
    product: mockProducts[1],
    title: 'Galaxy S24 Ultra',
    subtitle: 'L\'IA au service de votre créativité',
    imageUrl: mockProducts[1].images[0],
    order: 2,
    isActive: true,
  },
  {
    id: 'banner-3',
    productId: 'prod-4',
    product: mockProducts[3],
    title: 'iPad Pro',
    subtitle: 'Surpuissant. Superpolyvalent.',
    imageUrl: mockProducts[3].images[0],
    order: 3,
    isActive: true,
  },
];

export const mockOrders: Order[] = [
  {
    id: 'ORD-001',
    userId: 'user-1',
    items: [
      {
        productId: 'prod-6',
        quantity: 1,
        product: mockProducts[5],
      },
    ],
    total: 249,
    discount: 0,
    finalTotal: 249,
    status: 'delivered',
    shippingAddress: {
      name: 'User Demo',
      phone: '+33612345678',
      address: '123 Rue de la Paix',
      city: 'Paris',
    },
    loyaltyPointsEarned: 24,
    qrCode: 'QR-ORD-001',
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'ORD-002',
    userId: 'user-1',
    items: [
      {
        productId: 'prod-8',
        quantity: 1,
        product: mockProducts[7],
      },
    ],
    total: 799,
    discount: 0,
    finalTotal: 799,
    status: 'pending',
    shippingAddress: {
      name: 'User Demo',
      phone: '+33612345678',
      address: '123 Rue de la Paix',
      city: 'Paris',
    },
    loyaltyPointsEarned: 79,
    qrCode: 'QR-ORD-002',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
