name: 🚀 Deploy Backend to VPS

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'  # Déclenche uniquement si le backend change de truc
  workflow_dispatch:  # Permet de déclencher manuellement

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🚀 Deploy Backend to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          timeout: 60s
          command_timeout: 10m
          script: |
            cd /home/phone/app/backend
            git pull origin main
            npm install --production
            pm2 restart mon-backend

        
